services:
  - name: exam-akademi-akupunktur-surabaya
    type: web
    runtime: node
    repo: https://github.com/adminpendidikanaasoperator-maker/Exambrowser
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20